//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KT_6.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Addres
    {
        public int id { get; set; }
        public int id_index { get; set; }
        public int id_city { get; set; }
        public int id_street { get; set; }
        public Nullable<int> num_street { get; set; }
    
        public virtual City City { get; set; }
        public virtual Index Index { get; set; }
        public virtual Street Street { get; set; }
    }
}
